export const PRODUCT_REDUCER_ACTIONS = {
  CHANGE_PRODUCT_NAME: "CHANGE_PRODUCT_NAME",
  CHANGE_PRODUCT_CATEGORY: "CHANGE_PRODUCT_CATEGORY",
  CHANGE_PRODUCT_ORIGINAL_PRICE: "CHANGE_PRODUCT_ORIGINAL_PRICE",
  CHANGE_PRODUCT_DISCOUNT_PRICE: "CHANGE_PRODUCT_DISCOUNT_PRICE",
  CHANGE_PRODUCT_STOCK_UNITS: "CHANGE_PRODUCT_STOCK_UNITS",
  RESET_STATE: "RESET_STATE",
};

export const PRODUCT_FORM_IDS = {
  PRODUCT_NAME: "productName",
  PRODUCT_CATEGORY: "productCategory",
  PRODUCT_ORIGINAL_PRICE: "productOriginalPrice",
  PRODUCT_DISCOUNT_PRICE: "productDiscountPrice",
  PRODUCT_STOCK_UNITS: "productStockUnits",
};

export const PRODUCT_ADDITION_SUCCESS_MESSAGE = "New Product Added Succesfully";

export const PRODUCT_ADDITION_FAILURE_MESSAGE = "Please fill all Details correctly";

export const PRODUCT_CATEGORY_OPTIONS = [
  { label: "Mobiles", value: "mobiles" },
  { label: "TVs", value: "tvs" },
];

export const EventIDActionsType = new Map([
  [PRODUCT_FORM_IDS.PRODUCT_NAME, PRODUCT_REDUCER_ACTIONS.CHANGE_PRODUCT_NAME],
  [PRODUCT_FORM_IDS.PRODUCT_CATEGORY, PRODUCT_REDUCER_ACTIONS.CHANGE_PRODUCT_CATEGORY],
  [PRODUCT_FORM_IDS.PRODUCT_ORIGINAL_PRICE, PRODUCT_REDUCER_ACTIONS.CHANGE_PRODUCT_ORIGINAL_PRICE],
  [PRODUCT_FORM_IDS.PRODUCT_DISCOUNT_PRICE, PRODUCT_REDUCER_ACTIONS.CHANGE_PRODUCT_DISCOUNT_PRICE],
  [PRODUCT_FORM_IDS.PRODUCT_STOCK_UNITS, PRODUCT_REDUCER_ACTIONS.CHANGE_PRODUCT_STOCK_UNITS],
]);
